# Site settings
title: "Unch !!"
bye_message: "Thx!"
url: "https://unch.pw"

# Header settings
nick: "sahabatpakpos"
mail:
    domain: "unch"
    ext: "pw"
source_code:
    server: "github.com"
    nick: "sahabatpakpos"
blog:
    server: "github.com"
    nick: "sahabatpakpos"
# Build settings
markdown: kramdown
permalink: /:categories/:title/
