# Site settings
title: "unch.pw"
bye_message: "Common sense isn't actually common!"
baseurl: "/"
url: "https://unch.pw"
# Header settings
nick: "unch.pw"
mail:
    domain: "gmail"
    ext: "com"
source_code: 
    server: "github.com"
    nick: "sahabatpakpos"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
