# Site settings
title: "unch"
bye_message: "Thx!"
baseurl: "/"
url: "https://unch.pw"
disqus: unch

# Header settings
nick: "Sahabat_Pak_Pos"
mail:
    domain: "gmail"
    ext: "com"
source_code: 
    server: "github.com"
    nick: "sahabatpakpos"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
